# Configuration for ${project.name}
#
# Version: ${project.version}

# Debug information
debug-enabled: true

# Internal plugin prefix, used in console only.
plugin-prefix: '&3Minions &8>> '

# Path to language file
language: "lang/lang_en"

# Name of the folder that contains templates
template-folder: 'templates'

# Default values for templates
defaults:
  radius: 1
  action-interval: 10
  action-amount: 1